// Generates crates/zkpassport-core/src/oids_gen.rs from the TS OID tables
// (@zkpassport/utils cms/oids.ts + country/country.ts) so names cannot drift.
//
// Run from inside the utils package:
//   cd packages/zkpassport-utils && bun ../../rust/scripts/gen-oids.ts

import { writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { getOIDName, getHashAlgorithmName } from "../../packages/zkpassport-utils/src/cms/oids"
import { CURVE_OIDS } from "../../packages/zkpassport-utils/src/cms/constants"
import { countryCodeAlpha2ToAlpha3 } from "../../packages/zkpassport-utils/src/country/country"

// Signature algorithm OIDs the SOD/DSC parser can encounter
const SIG_ALG_OIDS = [
  "1.2.840.113549.1.1.1", // rsaEncryption
  "1.2.840.113549.1.1.5", // sha1WithRSAEncryption
  "1.2.840.113549.1.1.10", // RSASSA-PSS
  "1.2.840.113549.1.1.11", // sha256WithRSAEncryption
  "1.2.840.113549.1.1.12", // sha384WithRSAEncryption
  "1.2.840.113549.1.1.13", // sha512WithRSAEncryption
  "1.2.840.113549.1.1.14", // sha224WithRSAEncryption
  "1.2.840.10045.2.1", // ecPublicKey
  "1.2.840.10045.4.1", // ecdsa-with-SHA1
  "1.2.840.10045.4.3.1", // ecdsa-with-SHA224
  "1.2.840.10045.4.3.2", // ecdsa-with-SHA256
  "1.2.840.10045.4.3.3", // ecdsa-with-SHA384
  "1.2.840.10045.4.3.4", // ecdsa-with-SHA512
]

const HASH_ALG_OIDS = [
  "1.3.14.3.2.26", // sha1
  "2.16.840.1.101.3.4.2.4", // sha224
  "2.16.840.1.101.3.4.2.1", // sha256
  "2.16.840.1.101.3.4.2.2", // sha384
  "2.16.840.1.101.3.4.2.3", // sha512
]

const sigRows = SIG_ALG_OIDS.map((oid) => `        "${oid}" => Some("${getOIDName(oid)}"),`)
const hashRows = HASH_ALG_OIDS.map(
  (oid) => `        "${oid}" => Some("${getHashAlgorithmName(oid)}"),`,
)
const curveRows = Object.entries(CURVE_OIDS).map(
  ([oid, name]) => `        "${oid}" => Some("${name}"),`,
)

const A = "A".charCodeAt(0)
const countryRows: string[] = []
for (let i = 0; i < 26; i++) {
  for (let j = 0; j < 26; j++) {
    const a2 = String.fromCharCode(A + i) + String.fromCharCode(A + j)
    try {
      const a3 = countryCodeAlpha2ToAlpha3(a2)
      if (a3) countryRows.push(`        "${a2}" => Some("${a3}"),`)
    } catch {
      // not a country code
    }
  }
}

const out = `//! GENERATED by rust/scripts/gen-oids.ts from @zkpassport/utils cms/oids.ts
//! and country/country.ts. Do not edit by hand — regenerate instead.

/// getOIDName for signature/public-key algorithm OIDs.
pub fn sig_alg_name(oid: &str) -> Option<&'static str> {
    match oid {
${sigRows.join("\n")}
        _ => None,
    }
}

/// getHashAlgorithmName for digest algorithm OIDs.
pub fn hash_alg_name(oid: &str) -> Option<&'static str> {
    match oid {
${hashRows.join("\n")}
        _ => None,
    }
}

/// CURVE_OIDS: named-curve OID → curve name.
pub fn curve_oid_name(oid: &str) -> Option<&'static str> {
    match oid {
${curveRows.join("\n")}
        _ => None,
    }
}

/// countryCodeAlpha2ToAlpha3.
pub fn alpha2_to_alpha3(a2: &str) -> Option<&'static str> {
    match a2 {
${countryRows.join("\n")}
        _ => None,
    }
}
`

const path = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "crates",
  "zkpassport-core",
  "src",
  "oids_gen.rs",
)
writeFileSync(path, out)
console.log(
  `wrote ${sigRows.length} sig algs, ${hashRows.length} hashes, ${curveRows.length} curves, ${countryRows.length} countries → ${path}`,
)
