// Generates crates/zkpassport-core/src/curves_gen.rs from the TS curve tables
// (@zkpassport/utils cms/constants.ts) so the Rust constants cannot drift.
//
// Run from inside the utils package:
//   cd packages/zkpassport-utils && bun ../../rust/scripts/gen-curves.ts

import { writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import {
  NIST_CURVES,
  BRAINPOOL_CURVES,
} from "../../packages/zkpassport-utils/src/cms/constants"
import { getBitSizeFromCurve } from "../../packages/zkpassport-utils/src/cms/utils"

const entries: string[] = []
const paramRows: string[] = []
for (const [name, params] of [
  ...Object.entries(NIST_CURVES),
  ...Object.entries(BRAINPOOL_CURVES),
]) {
  const bits = getBitSizeFromCurve(name)
  const p = params as any
  entries.push(`        "${name}" => Some((${bits}, "${p.n.toString(16)}")),`)
  paramRows.push(
    `    ("${name}", "${p.a.toString(16)}", "${p.b.toString(16)}", "${p.n.toString(16)}", "${p.p.toString(16)}"),`,
  )
}

const out = `//! GENERATED by rust/scripts/gen-curves.ts from @zkpassport/utils cms/constants.ts.
//! Do not edit by hand — regenerate instead.

/// Returns (bit size, curve order n as hex) for a curve name.
pub fn curve_info(name: &str) -> Option<(u32, &'static str)> {
    match name {
${entries.join("\n")}
        _ => None,
    }
}

/// (name, a, b, n, p) as hex — for matching explicitly-specified curve params.
pub const CURVE_PARAMS: &[(&str, &str, &str, &str, &str)] = &[
${paramRows.join("\n")}
];
`

const path = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "crates",
  "zkpassport-core",
  "src",
  "curves_gen.rs",
)
writeFileSync(path, out)
console.log(`wrote ${entries.length} curves → ${path}`)
