//! Differential tests against the TypeScript oracle (@zkpassport/utils +
//! @zkpassport/poseidon2). Vectors are generated by rust/scripts/gen-vectors.ts:
//!
//!   bun rust/scripts/gen-vectors.ts
//!
//! Every ported function must produce output identical to the TS implementation.

use num_bigint::BigUint;
use serde_json::json;
use serde::Deserialize;
use zkpassport_core::{
    barrett, bytes, commitments, disclosure, dsc, id_data, input_gen, integrity, poseidon2,
    registry, select, signature, sod,
};

/// Minimal base64 decode (standard alphabet, padded) to avoid a dev-dependency.
fn base64_decode(s: &str) -> Vec<u8> {
    const ALPHABET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut lookup = [255u8; 256];
    for (i, &c) in ALPHABET.iter().enumerate() {
        lookup[c as usize] = i as u8;
    }
    let mut out = Vec::new();
    let mut buf: u32 = 0;
    let mut bits = 0;
    for &c in s.as_bytes() {
        if c == b'=' || c == b'\n' || c == b'\r' {
            continue;
        }
        let v = lookup[c as usize];
        assert_ne!(v, 255, "invalid base64 char");
        buf = (buf << 6) | v as u32;
        bits += 6;
        if bits >= 8 {
            bits -= 8;
            out.push((buf >> bits) as u8);
        }
    }
    out
}

#[derive(Deserialize)]
struct Vectors {
    redc: Vec<RedcCase>,
    #[serde(rename = "packBeField")]
    pack_be_field: Vec<PackFieldCase>,
    #[serde(rename = "packBeBits")]
    pack_be_bits: Vec<PackBitsCase>,
    #[serde(rename = "packBeFields")]
    pack_be_fields: Vec<PackFieldsCase>,
    #[serde(rename = "packLeFields")]
    pack_le_fields: Vec<PackFieldsCase>,
    poseidon2: Vec<PoseidonCase>,
    commitments: CommitmentCases,
    ecdsa: Vec<EcdsaCase>,
    integrity: Vec<IntegrityCase>,
    #[serde(rename = "idData")]
    id_data: Vec<IdDataCase>,
    #[serde(rename = "leafSamples")]
    leaf_samples: Vec<LeafSampleCase>,
    #[serde(rename = "dscMeta")]
    dsc_meta: DscMetaJson,
    dsc: Vec<DscCase>,
    age: Vec<AgeCase>,
    sod: Vec<SodCase>,
    #[serde(rename = "scopeHashes")]
    scope_hashes: Vec<ScopeHashCase>,
    #[serde(rename = "circuitNames")]
    circuit_names: Vec<CircuitNamesCase>,
    #[serde(rename = "publicSalts")]
    public_salts: Vec<PublicSaltCase>,
    disclosures: Vec<DisclosureCase>,
    #[serde(rename = "numPub")]
    num_pub: Vec<NumPubCase>,
    #[serde(rename = "ultraVk")]
    ultra_vk: UltraVkCase,
    #[serde(rename = "proofData2")]
    proof_data2: ProofDataCase,
    #[serde(rename = "circuitMerkle")]
    circuit_merkle: CircuitMerkleCase,
    #[serde(rename = "outerInputs")]
    outer_inputs: OuterInputsCase,
}

#[derive(Deserialize)]
struct NumPubCase {
    name: String,
    count: usize,
}
#[derive(Deserialize)]
struct UltraVkCase {
    bytes: Vec<u8>,
    result: Vec<String>,
}
#[derive(Deserialize)]
struct ProofDataCase {
    proof: String,
    num: usize,
    result: serde_json::Value,
}
#[derive(Deserialize)]
struct CircuitMerkleCase {
    key_hash: String,
    index: u64,
    path: Vec<String>,
    leaf_count: usize,
}
#[derive(Deserialize)]
struct OuterInputsCase {
    circuit_root: String,
    result: serde_json::Value,
}

#[derive(Deserialize)]
struct DisclosureCase {
    label: String,
    kind: String,
    master_salt: String,
    #[serde(default)]
    fields: std::collections::HashMap<String, bool>,
    #[serde(default)]
    min: i64,
    #[serde(default)]
    max: i64,
    #[serde(default)]
    countries: Vec<String>,
    #[serde(default)]
    user_address: String,
    #[serde(default)]
    custom_data: String,
    expected: serde_json::Value,
}

#[derive(Deserialize)]
struct PublicSaltCase {
    salt: String,
    result: String,
}

#[derive(Deserialize)]
struct CircuitNamesCase {
    name: String,
    expected: serde_json::Value,
}

#[derive(Deserialize)]
struct ScopeHashCase {
    value: String,
    result: String,
}

#[derive(Deserialize)]
struct SodExpected {
    e_content: Vec<u8>,
    signed_attributes: Vec<u8>,
    signer_signature: Vec<u8>,
    signer_sig_alg: String,
    signer_sig_alg_params: Option<Vec<u8>>,
    signer_digest_alg: String,
    dg_hash_alg: String,
    dg_hashes: Vec<(u32, Vec<u8>)>,
    tbs_certificate: Vec<u8>,
    cert_sig_alg: String,
    cert_signature: Vec<u8>,
    dsc_country: String,
    signature_type: String,
    public_key: serde_json::Value,
}

#[derive(Deserialize)]
struct SodCase {
    name: String,
    sod_base64: String,
    expected: SodExpected,
}

#[derive(Deserialize)]
struct AgeQueryJson {
    gt: Option<u32>,
    gte: Option<u32>,
    lt: Option<u32>,
    lte: Option<u32>,
    range: Option<(u32, u32)>,
    eq: Option<u32>,
}

#[derive(Deserialize)]
struct AgeCase {
    name: String,
    dg1: Vec<u8>,
    e_content: Vec<u8>,
    sod_signature_processed: Vec<u8>,
    dg2_hash: Vec<u8>,
    expiry_date: String,
    query: AgeQueryJson,
    salts: SaltsJson,
    service_scope: String,
    service_subscope: String,
    current_date: u64,
    expected: serde_json::Value,
}

#[derive(Deserialize)]
struct LeafSampleCase {
    cert: registry::PackagedCertificate,
    version: u32,
    result: String,
}

#[derive(Deserialize)]
struct DscMetaJson {
    version: u32,
    root: String,
    timestamp: u64,
    revocations: Vec<registry::Revocation>,
    masterlists: Vec<String>,
    cert_leaves: Vec<String>,
}

#[derive(Deserialize)]
struct DscCase {
    name: String,
    tbs_certificate: Vec<u8>,
    dsc_signature: Vec<u8>,
    csca: registry::PackagedCertificate,
    pss_salt_len: u32,
    salt: String,
    expected: serde_json::Value,
}

#[derive(Deserialize)]
struct RsaKeyJson {
    modulus: String,
    exponent: u64,
}

#[derive(Deserialize)]
struct EcdsaKeyJson {
    public_key: Vec<u8>,
    n: String,
    byte_size: usize,
}

#[derive(Deserialize)]
struct IdDataCase {
    name: String,
    dg1: Vec<u8>,
    e_content: Vec<u8>,
    signed_attributes: Vec<u8>,
    sod_signature: Vec<u8>,
    tbs_certificate: Vec<u8>,
    dsc_country: String,
    rsa: Option<RsaKeyJson>,
    ecdsa: Option<EcdsaKeyJson>,
    pss_salt_len: u32,
    salt_in: String,
    salt_out: String,
    expected: serde_json::Value,
}

#[derive(Deserialize)]
struct CommitmentCases {
    salted_bytes: SaltedBytesCase,
    salted_scalar: SaltedScalarCase,
    private_nullifier: PrivateNullifierCase,
    salt_country_tbs: SaltCountryTbsCase,
    comm_in: CommInCase,
    pack_le_hash: PackLeHashCase,
    salt_dg1_dg2: SaltDg1Dg2Case,
}

#[derive(Deserialize)]
struct SaltedBytesCase {
    salt: String,
    bytes: Vec<u8>,
    result: String,
}

#[derive(Deserialize)]
struct SaltedScalarCase {
    salt: String,
    value: String,
    result: String,
}

#[derive(Deserialize)]
struct PrivateNullifierCase {
    dg1: Vec<u8>,
    e_content: Vec<u8>,
    sod_sig: Vec<u8>,
    result: String,
}

#[derive(Deserialize)]
struct SaltCountryTbsCase {
    salt: String,
    country: String,
    tbs_padded: Vec<u8>,
    result: String,
}

#[derive(Deserialize)]
struct CommInCase {
    salt: String,
    country: String,
    padded_signed_attr: Vec<u8>,
    signed_attr_size: u64,
    dg1: Vec<u8>,
    e_content: Vec<u8>,
    private_nullifier: String,
    result: String,
}

#[derive(Deserialize)]
struct PackLeHashCase {
    bytes: Vec<u8>,
    result: String,
}

#[derive(Deserialize)]
struct SaltsJson {
    dg1_salt: String,
    expiry_date_salt: String,
    dg2_hash_salt: String,
    private_nullifier_salt: String,
}

impl SaltsJson {
    fn to_salts(&self) -> commitments::IntegrityToDisclosureSalts {
        commitments::IntegrityToDisclosureSalts {
            dg1_salt: dec_or_hex(&self.dg1_salt),
            expiry_date_salt: dec_or_hex(&self.expiry_date_salt),
            dg2_hash_salt: dec_or_hex(&self.dg2_hash_salt),
            private_nullifier_salt: dec_or_hex(&self.private_nullifier_salt),
        }
    }
}

#[derive(Deserialize)]
struct SaltDg1Dg2Case {
    salts: SaltsJson,
    dg1: Vec<u8>,
    expiry_date: String,
    dg2_hash_normalized: String,
    dg2_hash_type: u32,
    private_nullifier: String,
    result: String,
}

#[derive(Deserialize)]
struct EcdsaCase {
    signature: Vec<u8>,
    byte_size: usize,
    n: String,
    result: Vec<u8>,
}

#[derive(Deserialize)]
struct IntegrityCase {
    name: String,
    dg1: Vec<u8>,
    e_content: Vec<u8>,
    signed_attributes: Vec<u8>,
    sod_signature_processed: Vec<u8>,
    dsc_country: String,
    salt_in: String,
    salts: SaltsJson,
    expected: serde_json::Value,
}

#[derive(Deserialize)]
struct RedcCase {
    input: Vec<u8>,
    output: Vec<u8>,
}

#[derive(Deserialize)]
struct PackFieldCase {
    bytes: Vec<u8>,
    max_field_size: usize,
    result: String,
}

#[derive(Deserialize)]
struct PackBitsCase {
    bits: Vec<u8>,
    max_field_size: usize,
    result: String,
}

#[derive(Deserialize)]
struct PackFieldsCase {
    bytes: Vec<u8>,
    max_chunk_size: usize,
    result: Vec<String>,
}

#[derive(Deserialize)]
struct PoseidonCase {
    inputs: Vec<String>,
    result: String,
}

fn load() -> Vectors {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../vectors/vectors.json");
    let data = std::fs::read_to_string(path)
        .expect("vectors.json missing — run `bun rust/scripts/gen-vectors.ts` first");
    serde_json::from_str(&data).expect("vectors.json parse")
}

fn dec(s: &str) -> BigUint {
    s.parse().expect("decimal bigint")
}

fn dec_or_hex(s: &str) -> BigUint {
    if let Some(hex) = s.strip_prefix("0x") {
        BigUint::parse_bytes(hex.as_bytes(), 16).expect("hex bigint")
    } else {
        dec(s)
    }
}

#[test]
fn redc_limbs_matches_ts() {
    for (i, case) in load().redc.iter().enumerate() {
        let got = barrett::redc_limbs_from_bytes(&case.input);
        assert_eq!(got, case.output, "redc case {i}");
    }
}

#[test]
fn pack_be_bytes_into_field_matches_ts() {
    for (i, case) in load().pack_be_field.iter().enumerate() {
        let got = bytes::pack_be_bytes_into_field(&case.bytes, case.max_field_size);
        assert_eq!(got, dec(&case.result), "packBeField case {i}");
    }
}

#[test]
fn pack_be_bits_into_field_matches_ts() {
    for (i, case) in load().pack_be_bits.iter().enumerate() {
        let got = bytes::pack_be_bits_into_field(&case.bits, case.max_field_size);
        assert_eq!(got, dec(&case.result), "packBeBits case {i}");
    }
}

#[test]
fn pack_be_bytes_into_fields_matches_ts() {
    for (i, case) in load().pack_be_fields.iter().enumerate() {
        let got = bytes::pack_be_bytes_into_fields(&case.bytes, case.max_chunk_size);
        assert_eq!(got, case.result, "packBeFields case {i}");
    }
}

#[test]
fn pack_le_bytes_into_fields_matches_ts() {
    for (i, case) in load().pack_le_fields.iter().enumerate() {
        let got = bytes::pack_le_bytes_into_fields(&case.bytes, case.max_chunk_size);
        assert_eq!(got, case.result, "packLeFields case {i}");
    }
}

#[test]
fn poseidon2_hash_matches_ts() {
    for (i, case) in load().poseidon2.iter().enumerate() {
        let inputs: Vec<BigUint> = case.inputs.iter().map(|s| dec(s)).collect();
        let got = poseidon2::poseidon2_hash(&inputs);
        assert_eq!(got, dec(&case.result), "poseidon2 case {i}");
    }
}

#[test]
fn commitment_primitives_match_ts() {
    let c = load().commitments;

    let sb = &c.salted_bytes;
    assert_eq!(
        commitments::salted_value_hash_bytes(&dec_or_hex(&sb.salt), &sb.bytes),
        dec(&sb.result),
        "salted_bytes"
    );

    let ss = &c.salted_scalar;
    assert_eq!(
        commitments::salted_value_hash_scalar(&dec_or_hex(&ss.salt), &dec(&ss.value)),
        dec(&ss.result),
        "salted_scalar"
    );

    let pn = &c.private_nullifier;
    assert_eq!(
        commitments::calculate_private_nullifier(&pn.dg1, &pn.e_content, &pn.sod_sig),
        dec(&pn.result),
        "private_nullifier"
    );

    let st = &c.salt_country_tbs;
    assert_eq!(
        commitments::hash_salt_country_tbs(&dec_or_hex(&st.salt), &st.country, &st.tbs_padded),
        dec(&st.result),
        "salt_country_tbs"
    );

    let ci = &c.comm_in;
    assert_eq!(
        commitments::hash_salt_country_signed_attr_dg1_e_content_private_nullifier(
            &dec_or_hex(&ci.salt),
            &ci.country,
            &ci.padded_signed_attr,
            &BigUint::from(ci.signed_attr_size),
            &ci.dg1,
            &ci.e_content,
            &dec(&ci.private_nullifier),
        ),
        dec(&ci.result),
        "comm_in"
    );

    let pl = &c.pack_le_hash;
    assert_eq!(
        commitments::pack_le_bytes_and_hash_poseidon2(&pl.bytes),
        dec(&pl.result),
        "pack_le_hash"
    );

    let sd = &c.salt_dg1_dg2;
    assert_eq!(
        commitments::hash_salt_dg1_dg2_hash_private_nullifier(
            &sd.salts.to_salts(),
            &sd.dg1,
            &sd.expiry_date,
            &dec(&sd.dg2_hash_normalized),
            sd.dg2_hash_type,
            &dec(&sd.private_nullifier),
        ),
        dec(&sd.result),
        "salt_dg1_dg2"
    );
}

#[test]
fn process_ecdsa_signature_matches_ts() {
    for (i, case) in load().ecdsa.iter().enumerate() {
        let got =
            signature::process_ecdsa_signature(&case.signature, case.byte_size, &dec(&case.n));
        assert_eq!(got, case.result, "ecdsa case {i}");
    }
}

#[test]
fn id_data_circuit_inputs_match_ts() {
    for case in load().id_data.iter() {
        let dsc_pubkey = if let Some(rsa) = &case.rsa {
            id_data::DscPublicKey::Rsa {
                modulus: dec(&rsa.modulus).to_bytes_be(),
                exponent: rsa.exponent,
            }
        } else {
            let ec = case.ecdsa.as_ref().expect("rsa or ecdsa key");
            id_data::DscPublicKey::Ecdsa {
                public_key: ec.public_key.clone(),
                curve_n: dec(&ec.n),
                curve_byte_size: ec.byte_size,
            }
        };
        let input = id_data::IdDataInput {
            dg1: &case.dg1,
            e_content: &case.e_content,
            signed_attributes: &case.signed_attributes,
            sod_signature: &case.sod_signature,
            tbs_certificate: &case.tbs_certificate,
            dsc_country: &case.dsc_country,
            dsc_pubkey,
            pss_salt_len: case.pss_salt_len,
        };
        let got = id_data::get_id_data_circuit_inputs(
            &input,
            &dec(&case.salt_in),
            &dec(&case.salt_out),
        );
        assert_eq!(got, case.expected, "id_data fixture '{}'", case.name);
    }
}

#[test]
fn certificate_leaf_hash_matches_ts() {
    for (i, case) in load().leaf_samples.iter().enumerate() {
        let got = registry::get_certificate_leaf_hash(
            &case.cert,
            registry::CERT_TYPE_CSCA,
            case.version,
        )
        .expect("leaf hash");
        assert_eq!(got, dec(&case.result), "leaf sample {i}");
    }
}

#[test]
fn dsc_circuit_inputs_match_ts() {
    let v = load();
    let leaves: Vec<BigUint> = v.dsc_meta.cert_leaves.iter().map(|s| dec(s)).collect();
    let meta = dsc::PackagedCertsMeta {
        version: v.dsc_meta.version,
        root: &v.dsc_meta.root,
        timestamp: v.dsc_meta.timestamp,
        revocations: &v.dsc_meta.revocations,
        masterlists: &v.dsc_meta.masterlists,
    };
    for case in v.dsc.iter() {
        let input = dsc::DscInput {
            tbs_certificate: &case.tbs_certificate,
            dsc_signature: &case.dsc_signature,
            pss_salt_len: case.pss_salt_len,
        };
        let got = dsc::get_dsc_circuit_inputs(&input, &dec(&case.salt), &case.csca, &meta, &leaves)
            .expect("dsc inputs");
        assert_eq!(got, case.expected, "dsc fixture '{}'", case.name);
    }
}

#[test]
fn age_circuit_inputs_match_ts() {
    for case in load().age.iter() {
        let mrz = zkpassport_core::input_gen::mrz_from_dg1(&case.dg1).expect("mrz");
        let input = disclosure::DisclosureInput {
            dg1: &case.dg1,
            e_content: &case.e_content,
            sod_signature_processed: &case.sod_signature_processed,
            dg2_hash: &case.dg2_hash,
            expiry_date: &case.expiry_date,
            mrz: &mrz,
        };
        let query = disclosure::AgeQuery {
            gt: case.query.gt,
            gte: case.query.gte,
            lt: case.query.lt,
            lte: case.query.lte,
            range: case.query.range,
            eq: case.query.eq,
            disclose_age: None,
        };
        let got = disclosure::get_age_circuit_inputs(
            &input,
            &query,
            &case.salts.to_salts(),
            &BigUint::from(0u8),
            &dec(&case.service_scope),
            &dec(&case.service_subscope),
            case.current_date,
            None,
        )
        .expect("age inputs");
        assert_eq!(got, case.expected, "age fixture '{}'", case.name);
    }
}

#[test]
fn sod_parsing_matches_ts() {
    for case in load().sod.iter() {
        let der = base64_decode(&case.sod_base64);
        let parsed = sod::parse_sod(&der).expect("parse SOD");
        let exp = &case.expected;
        let n = &case.name;
        assert_eq!(parsed.e_content, exp.e_content, "{n}: e_content");
        assert_eq!(
            parsed.signed_attributes, exp.signed_attributes,
            "{n}: signed_attributes"
        );
        assert_eq!(
            parsed.signer_signature, exp.signer_signature,
            "{n}: signer_signature"
        );
        assert_eq!(parsed.signer_sig_alg, exp.signer_sig_alg, "{n}: signer_sig_alg");
        assert_eq!(
            parsed.signer_sig_alg_params, exp.signer_sig_alg_params,
            "{n}: signer_sig_alg_params"
        );
        assert_eq!(
            parsed.signer_digest_alg, exp.signer_digest_alg,
            "{n}: signer_digest_alg"
        );
        assert_eq!(parsed.dg_hash_alg, exp.dg_hash_alg, "{n}: dg_hash_alg");
        assert_eq!(parsed.dg_hashes, exp.dg_hashes, "{n}: dg_hashes");
        assert_eq!(
            parsed.tbs_certificate, exp.tbs_certificate,
            "{n}: tbs_certificate"
        );
        assert_eq!(parsed.cert_sig_alg, exp.cert_sig_alg, "{n}: cert_sig_alg");
        assert_eq!(parsed.cert_signature, exp.cert_signature, "{n}: cert_signature");
        assert_eq!(parsed.dsc_country, exp.dsc_country, "{n}: dsc_country");
        assert_eq!(parsed.signature_type(), exp.signature_type, "{n}: signature_type");
        match &parsed.public_key {
            sod::SodPublicKey::Rsa { modulus, exponent } => {
                assert_eq!(exp.public_key["type"], "rsa", "{n}: pk type");
                assert_eq!(
                    BigUint::from_bytes_be(modulus),
                    dec(exp.public_key["modulus"].as_str().unwrap()),
                    "{n}: modulus"
                );
                assert_eq!(
                    *exponent,
                    exp.public_key["exponent"].as_u64().unwrap(),
                    "{n}: exponent"
                );
            }
            sod::SodPublicKey::Ecdsa { public_key, curve } => {
                assert_eq!(exp.public_key["type"], "ecdsa", "{n}: pk type");
                let exp_pk: Vec<u8> = exp.public_key["public_key"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|v| v.as_u64().unwrap() as u8)
                    .collect();
                assert_eq!(*public_key, exp_pk, "{n}: ec public key");
                assert_eq!(curve, exp.public_key["curve"].as_str().unwrap(), "{n}: curve");
            }
        }
    }
}

#[test]
fn csca_matching_matches_ts() {
    // getCscaForPassportAsync's primary AKI/SKI path must select the same
    // CSCA the TS pipeline selected (compared by fingerprint).
    let fixtures = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../packages/zkpassport-utils/tests/fixtures/root-certs-v1.json"
    );
    let file: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(fixtures).expect("root-certs-v1.json"))
            .unwrap();
    let certs: Vec<registry::PackagedCertificate> =
        serde_json::from_value(file["certificates"].clone()).unwrap();
    let v = load();
    for sod_case in v.sod.iter() {
        let der = base64_decode(&sod_case.sod_base64);
        let parsed = sod::parse_sod(&der).expect("parse SOD");
        let matched = registry::match_csca(
            &certs,
            &parsed.dsc_country,
            parsed.authority_key_identifier.as_deref(),
        )
        .unwrap_or_else(|| panic!("{}: no CSCA matched", sod_case.name));
        let expected = v
            .dsc
            .iter()
            .find(|c| c.name == sod_case.name)
            .unwrap()
            .csca
            .fingerprint
            .clone();
        assert_eq!(matched.fingerprint, expected, "{}: csca", sod_case.name);
    }
}

#[test]
fn circuit_names_match_app_logic() {
    let v = load();
    for case in v.circuit_names.iter() {
        let sod_case = v.sod.iter().find(|s| s.name == case.name).unwrap();
        let dsc_case = v.dsc.iter().find(|c| c.name == case.name).unwrap();
        let der = base64_decode(&sod_case.sod_base64);
        let parsed = sod::parse_sod(&der).expect("parse SOD");
        let names =
            select::get_circuit_names(&parsed, &dsc_case.csca, false).expect("circuit names");
        assert_eq!(names.dsc, case.expected["dsc"].as_str().unwrap(), "{}: dsc", case.name);
        assert_eq!(
            names.id_data,
            case.expected["id_data"].as_str().unwrap(),
            "{}: id_data",
            case.name
        );
        assert_eq!(
            names.integrity,
            case.expected["integrity"].as_str().unwrap(),
            "{}: integrity",
            case.name
        );
        assert_eq!(names.age, case.expected["age"].as_str().unwrap(), "{}: age", case.name);
    }
}

#[test]
fn disclosure_builders_match_ts() {
    let v = load();
    for case in v.disclosures.iter() {
        let name = case.label.split(':').next().unwrap();
        // Reuse the passport raw fields from the matching age vector.
        let age = v.age.iter().find(|a| a.name == format!("{name}:gte18")).unwrap();
        let dg1 = &age.dg1;
        let mrz = zkpassport_core::input_gen::mrz_from_dg1(dg1).expect("mrz");
        let input = disclosure::DisclosureInput {
            dg1,
            e_content: &age.e_content,
            sod_signature_processed: &age.sod_signature_processed,
            dg2_hash: &age.dg2_hash,
            expiry_date: &age.expiry_date,
            mrz: &mrz,
        };
        let salts = input_gen::InputGenSalts::from_master(dec(&case.master_salt)).disclosure;
        let z = &BigUint::from(0u8);
        let got = match case.kind.as_str() {
            "disclose" => {
                let f = disclosure::DiscloseFields {
                    firstname: *case.fields.get("firstname").unwrap_or(&false),
                    document_type: *case.fields.get("document_type").unwrap_or(&false),
                    ..Default::default()
                };
                disclosure::get_disclose_circuit_inputs(&input, &f, &salts, z, z, z, 1789000000, None)
            }
            "birthdate" | "expiry" => {
                let bounds = disclosure::DateBounds {
                    min: if case.min != 0 { Some(case.min) } else { None },
                    max: if case.max != 0 { Some(case.max) } else { None },
                };
                disclosure::get_date_circuit_inputs(
                    &input, &bounds, case.kind == "birthdate", &salts, z, z, z, 1789000000, None,
                )
            }
            "nat_in" => disclosure::get_country_inclusion_circuit_inputs(
                &input, &case.countries, &salts, z, z, z, 1789000000, None,
            ),
            "issue_out" => disclosure::get_country_exclusion_circuit_inputs(
                &input, &case.countries, &salts, z, z, z, 1789000000, None,
            ),
            "bind" => {
                let bound = disclosure::BoundData {
                    user_address: Some(case.user_address.clone()),
                    custom_data: Some(case.custom_data.clone()),
                    chain_id: None,
                };
                disclosure::get_bind_circuit_inputs(&input, &bound, &salts, z, z, z, 1789000000, None)
            }
            other => panic!("unknown disclosure kind {other}"),
        }
        .unwrap_or_else(|e| panic!("{}: {e}", case.label));
        assert_eq!(got, case.expected, "disclosure {}", case.label);
    }
}

#[test]
fn outer_assembly_matches_ts() {
    use zkpassport_core::outer;
    let v = load();

    for c in v.num_pub.iter() {
        assert_eq!(outer::num_public_inputs(&c.name), c.count, "numPub {}", c.name);
    }

    // ultraVkToFields
    assert_eq!(
        outer::ultra_vk_to_fields(&v.ultra_vk.bytes),
        v.ultra_vk.result,
        "ultraVkToFields"
    );

    // getProofData
    let pd = outer::get_proof_data(&v.proof_data2.proof, v.proof_data2.num).unwrap();
    assert_eq!(json!(pd.proof), v.proof_data2.result["proof"], "proofData.proof");
    assert_eq!(json!(pd.public_inputs), v.proof_data2.result["publicInputs"], "proofData.publicInputs");

    // circuit merkle proof (against the manifest fixture)
    let manifest_path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../packages/zkpassport-utils/tests/fixtures/manifest.json"
    );
    let manifest: zkpassport_core::plan::CircuitManifest =
        serde_json::from_str(&std::fs::read_to_string(manifest_path).unwrap()).unwrap();
    let cm = &v.circuit_merkle;
    assert_eq!(outer::circuit_leaves(&manifest).len(), cm.leaf_count, "leaf count");
    let (index, path) = outer::circuit_merkle_proof(&manifest, &cm.key_hash).unwrap();
    assert_eq!(index, format!("0x{:x}", cm.index), "circuit tree index");
    assert_eq!(path, cm.path, "circuit tree path");

    // getOuterCircuitInputs — synthetic subproofs
    let ocp = |tag: &str, pis: &[&str]| outer::OuterSubproof {
        proof: vec![format!("0x{tag}1")],
        public_inputs: pis.iter().map(|s| s.to_string()).collect(),
        vkey: vec![format!("0x{tag}2")],
        key_hash: format!("0x{tag}3"),
        tree_hash_path: vec![format!("0x{tag}4"), format!("0x{tag}5")],
        tree_index: format!("0x{tag}6"),
    };
    let csc = ocp("a", &["0xa0", "0xa1", "0xa2"]);
    let dsc_id = ocp("b", &["0xb0", "0xb1"]);
    let integ = ocp("c", &["0xc0", "0xc1"]);
    let disc1 = ocp("d", &["0xd0", "0x64", "0xd2", "0xd3", "0xd4", "0xd5", "0x99", "0xd7"]);
    let disc2 = ocp("e", &["0xe0", "0x64", "0xe2", "0xe3", "0xe4", "0xe5", "0x0", "0xe7"]);
    let got = outer::get_outer_circuit_inputs(
        &csc, &dsc_id, &integ, &[disc1, disc2], &v.outer_inputs.circuit_root,
    )
    .unwrap();
    assert_eq!(got, v.outer_inputs.result, "getOuterCircuitInputs");
}

#[test]
fn public_salt_matches_ts() {
    for (i, case) in load().public_salts.iter().enumerate() {
        let got = input_gen::get_public_salt(&dec(&case.salt));
        assert_eq!(got, dec(&case.result), "public salt case {i}");
    }
}

#[test]
fn scope_hash_matches_ts() {
    for case in load().scope_hashes.iter() {
        assert_eq!(
            input_gen::scope_hash(&case.value),
            dec(&case.result),
            "scope hash '{}'",
            case.value
        );
    }
}

/// The full pipeline: raw SOD DER + DG1 + DG2 hash → all four circuit input
/// sets, each compared against the TS builder outputs captured above.
#[test]
fn end_to_end_input_generation_matches_ts() {
    let v = load();
    let leaves: Vec<BigUint> = v.dsc_meta.cert_leaves.iter().map(|s| dec(s)).collect();
    let meta = dsc::PackagedCertsMeta {
        version: v.dsc_meta.version,
        root: &v.dsc_meta.root,
        timestamp: v.dsc_meta.timestamp,
        revocations: &v.dsc_meta.revocations,
        masterlists: &v.dsc_meta.masterlists,
    };
    for sod_case in v.sod.iter() {
        let name = &sod_case.name;
        let age_case = v
            .age
            .iter()
            .find(|a| a.name == format!("{name}:gte18"))
            .expect("age case");
        let id_case = v.id_data.iter().find(|c| &c.name == name).expect("id case");
        let integ_case = v.integrity.iter().find(|c| &c.name == name).expect("integrity case");
        let dsc_case = v.dsc.iter().find(|c| &c.name == name).expect("dsc case");

        let der = base64_decode(&sod_case.sod_base64);
        let query = serde_json::json!({ "age": { "gte": 18 } });
        let params = input_gen::GenerateParams {
            sod_der: &der,
            dg1: &id_case.dg1,
            dg2_hash: &age_case.dg2_hash,
            csca: &dsc_case.csca,
            certs_meta: &meta,
            cert_leaves: &leaves,
            query: &query,
            evm: false,
            nullifier_secret: BigUint::from(0u8),
            service_scope: dec(&age_case.service_scope),
            service_subscope: dec(&age_case.service_subscope),
            current_date_timestamp: age_case.current_date,
        };
        let salts = input_gen::InputGenSalts {
            dsc_salt: dec(&dsc_case.salt),
            id_salt_in: dec(&id_case.salt_in),
            id_salt_out: dec(&id_case.salt_out),
            integrity_salt_in: dec(&integ_case.salt_in),
            disclosure: age_case.salts.to_salts(),
        };
        let out = input_gen::generate_all_inputs(&params, &salts).expect("generate inputs");
        assert_eq!(out["dsc"], dsc_case.expected, "{name}: dsc");
        assert_eq!(out["id_data"], id_case.expected, "{name}: id_data");
        assert_eq!(out["integrity"], integ_case.expected, "{name}: integrity");
        // Query-driven: age is now the single produced disclosure.
        let disc = &out["disclosures"].as_array().unwrap()[0];
        assert_eq!(disc["name"], "compare_age");
        assert_eq!(disc["inputs"], age_case.expected, "{name}: age");
    }
}

#[test]
fn integrity_circuit_inputs_match_ts() {
    for case in load().integrity.iter() {
        let data = integrity::IntegrityInputData {
            dg1: &case.dg1,
            e_content: &case.e_content,
            signed_attributes: &case.signed_attributes,
            sod_signature_processed: &case.sod_signature_processed,
            dsc_country: &case.dsc_country,
        };
        let got = integrity::get_integrity_check_circuit_inputs(
            &data,
            &dec(&case.salt_in),
            &case.salts.to_salts(),
        );
        assert_eq!(got, case.expected, "integrity fixture '{}'", case.name);
    }
}
