import { defineConfig } from "tsup"

const isDev = process.env.DEV_BUILD === "true"

export default defineConfig(
  (["esm", "cjs"] as const).map((format) => ({
    entry: {
      "index": "src/index.ts",
      "barrett-reduction": "src/barrett-reduction.ts",
      "circuit-matcher": "src/circuit-matcher.ts",
      "recursion": "src/recursion.ts",
      "rsa": "src/rsa.ts",
      "utils": "src/utils.ts",
      "binary/index": "src/binary/index.ts",
      "cms/index": "src/cms/index.ts",
      "cms/asn": "src/cms/asn.ts",
      "country/country": "src/country/country.ts",
      "circuits/index": "src/circuits/index.ts",
      "constants/index": "src/constants/index.ts",
      "merkle-tree/index": "src/merkle-tree/index.ts",
      "passport/index": "src/passport/index.ts",
      "registry/index": "src/registry/index.ts",
      "types/index": "src/types/index.ts",
    },
    dts: false, // Types generated by tsc -b in the types step
    clean: true,
    format,
    outDir: `dist/${format}`,
    outExtension: () => ({ js: format === "cjs" ? ".cjs" : ".js" }),
    splitting: false,
    sourcemap: true,
    treeshake: !isDev,
    // No workspace dependencies to externalize for utils (it's the base package)
  })),
)
