
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import ZKPassportRegistryContractArtifactJson from '../../../zkpassport.nr/target/zkpassport_registry_contract-ZKPassportRegistry.json' with { type: 'json' };
export const ZKPassportRegistryContractArtifact = loadContractArtifact(ZKPassportRegistryContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract ZKPassportRegistry;
 */
export class ZKPassportRegistryContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, ZKPassportRegistryContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): ZKPassportRegistryContract {
    return Contract.at(address, ZKPassportRegistryContract.artifact, wallet) as ZKPassportRegistryContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike, oracle: AztecAddressLike, guardian: AztecAddressLike, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<ZKPassportRegistryContract>(
      wallet,
      {
        artifact: ZKPassportRegistryContractArtifact,
        postDeployCtor: (instance, wallet) => ZKPassportRegistryContract.at(instance.address, wallet),
        args: [admin, oracle, guardian],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof ZKPassportRegistryContract['methods']>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions },
    ...args: Parameters<ZKPassportRegistryContract['methods'][M]>
  ) {
    return DeployMethod.create<ZKPassportRegistryContract>(
      opts.wallet,
      {
        artifact: ZKPassportRegistryContractArtifact,
        postDeployCtor: (instance, wallet) => ZKPassportRegistryContract.at(instance.address, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? 'constructor',
      },
      opts.instantiation,
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return ZKPassportRegistryContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(ZKPassportRegistryContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'admin' | 'oracle' | 'guardian' | 'paused' | 'config' | 'latest' | 'roots' | 'accepted_vks' | 'oprf_pk_hash'> {
      return {
        admin: {
      slot: new Fr(1n),
    },
oracle: {
      slot: new Fr(2n),
    },
guardian: {
      slot: new Fr(3n),
    },
paused: {
      slot: new Fr(4n),
    },
config: {
      slot: new Fr(8n),
    },
latest: {
      slot: new Fr(9n),
    },
roots: {
      slot: new Fr(10n),
    },
accepted_vks: {
      slot: new Fr(11n),
    },
oprf_pk_hash: {
      slot: new Fr(12n),
    }
      } as ContractStorageLayout<'admin' | 'oracle' | 'guardian' | 'paused' | 'config' | 'latest' | 'roots' | 'accepted_vks' | 'oprf_pk_hash'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** add_accepted_vk(vk_hash: field) */
    add_accepted_vk: ((vk_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** assert_proof_valid(vk_hash: field, cert_root: field, circuit_root: field, current_date: integer, nullifier_type: integer, oprf_pk_hash: field) */
    assert_proof_valid: ((vk_hash: FieldLike, cert_root: FieldLike, circuit_root: FieldLike, current_date: (bigint | number), nullifier_type: (bigint | number), oprf_pk_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** assert_root_valid_at_timestamp(registry_id: field, root: field, timestamp: integer) */
    assert_root_valid_at_timestamp: ((registry_id: FieldLike, root: FieldLike, timestamp: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** assert_sanctions_root_valid(root: field, current_date: integer) */
    assert_sanctions_root_valid: ((root: FieldLike, current_date: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** batch_update_roots(registry_id: field, roots: array, count: integer) */
    batch_update_roots: ((registry_id: FieldLike, roots: { root: FieldLike, valid_from: (bigint | number), valid_to: (bigint | number), revoked: boolean }[], count: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(admin: struct, oracle: struct, guardian: struct) */
    constructor: ((admin: AztecAddressLike, oracle: AztecAddressLike, guardian: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_latest_pair(registry_id: field) */
    get_latest_pair: ((registry_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_vk_accepted(vk_hash: field) */
    is_vk_accepted: ((vk_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** pause() */
    pause: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** remove_accepted_vk(vk_hash: field) */
    remove_accepted_vk: ((vk_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_guardian(new_guardian: struct) */
    set_guardian: ((new_guardian: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_oprf_pk_hash(oprf_pk_hash: field) */
    set_oprf_pk_hash: ((oprf_pk_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_oracle(new_oracle: struct) */
    set_oracle: ((new_oracle: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_revocation_status(registry_id: field, root: field, revoked: boolean) */
    set_revocation_status: ((registry_id: FieldLike, root: FieldLike, revoked: boolean) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_root_validation_mode(registry_id: field, mode: integer) */
    set_root_validation_mode: ((registry_id: FieldLike, mode: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_validity_window(registry_id: field, window: integer) */
    set_validity_window: ((registry_id: FieldLike, window: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_admin(new_admin: struct) */
    transfer_admin: ((new_admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** unpause() */
    unpause: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_root(registry_id: field, new_root: field, current_root: field, timestamp: integer) */
    update_root: ((registry_id: FieldLike, new_root: FieldLike, current_root: FieldLike, timestamp: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
