// Fixture JSON -> Noir globals for TXE tests. Usage: bun fixture-to-noir.ts <fixture.json> <out.nr>
import { readFileSync, writeFileSync } from "fs"

const [fixturePath, outPath] = process.argv.slice(2)
const fx = JSON.parse(readFileSync(fixturePath, "utf8"))
const blob: string[] = [...fx.vkeyFields, ...fx.proof, ...fx.publicInputs] // capsule layout: vk ‖ proof ‖ PIs

const arr = (name: string, values: string[]) =>
  `pub global ${name}: [Field; ${values.length}] = [\n    ${values.join(",\n    ")},\n];\n`

writeFileSync(
  outPath,
  "// GENERATED by test-harness/fixture-to-noir.ts — do not edit\n" +
    arr("AGE_FIXTURE_BLOB", blob) +
    `pub global AGE_FIXTURE_CERT_ROOT: Field = ${fx.certificateRegistryRoot};\n` +
    `pub global AGE_FIXTURE_CIRCUIT_ROOT: Field = ${fx.circuitRegistryRoot};\n` +
    `pub global AGE_FIXTURE_VK_HASH: Field = ${fx.vkeyHashBB};\n` +
    `pub global AGE_FIXTURE_CURRENT_DATE: u64 = ${fx.nowTimestamp};\n`,
)
console.log("wrote", outPath)
