#!/usr/bin/env python3
"""Fixture JSON -> Noir globals for TXE tests. Usage: fixture_to_noir.py <fixture.json> <out.nr>"""
import json, sys

fx = json.load(open(sys.argv[1]))
blob = fx["vkeyFields"] + fx["proof"] + fx["publicInputs"]  # capsule layout: vk ‖ proof ‖ PIs

def arr(name, values):
    body = ",\n    ".join(str(v) for v in values)
    return f"pub global {name}: [Field; {len(values)}] = [\n    {body},\n];\n"

with open(sys.argv[2], "w") as f:
    f.write("// GENERATED by test-harness/fixture_to_noir.py — do not edit\n")
    f.write(arr("AGE_FIXTURE_BLOB", blob))
    f.write(f"pub global AGE_FIXTURE_CERT_ROOT: Field = {fx['certificateRegistryRoot']};\n")
    f.write(f"pub global AGE_FIXTURE_CIRCUIT_ROOT: Field = {fx['circuitRegistryRoot']};\n")
    f.write(f"pub global AGE_FIXTURE_VK_HASH: Field = {fx['vkeyHashBB']};\n")
    f.write(f"pub global AGE_FIXTURE_CURRENT_DATE: u64 = {fx['nowTimestamp']};\n")
print("wrote", sys.argv[2])
