//! GENERATED by rust/scripts/gen-curves.ts from @zkpassport/utils cms/constants.ts.
//! Do not edit by hand — regenerate instead.

/// Returns (bit size, curve order n as hex) for a curve name.
pub fn curve_info(name: &str) -> Option<(u32, &'static str)> {
    match name {
        "P-192" => Some((192, "ffffffffffffffffffffffff99def836146bc9b1b4d22831")),
        "P-224" => Some((224, "ffffffffffffffffffffffffffff16a2e0b8f03e13dd29455c5c2a3d")),
        "P-256" => Some((256, "ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551")),
        "P-384" => Some((384, "ffffffffffffffffffffffffffffffffffffffffffffffffc7634d81f4372ddf581a0db248b0a77aecec196accc52973")),
        "P-521" => Some((521, "1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffa51868783bf2f966b7fcc0148f709a5d03bb5c9b8899c47aebb6fb71e91386409")),
        "brainpoolP160r1" => Some((160, "e95e4a5f737059dc60df5991d45029409e60fc09")),
        "brainpoolP160t1" => Some((160, "e95e4a5f737059dc60df5991d45029409e60fc09")),
        "brainpoolP192r1" => Some((192, "c302f41d932a36cda7a3462f9e9e916b5be8f1029ac4acc1")),
        "brainpoolP192t1" => Some((192, "c302f41d932a36cda7a3462f9e9e916b5be8f1029ac4acc1")),
        "brainpoolP224r1" => Some((224, "d7c134aa264366862a18302575d0fb98d116bc4b6ddebca3a5a7939f")),
        "brainpoolP224t1" => Some((224, "d7c134aa264366862a18302575d0fb98d116bc4b6ddebca3a5a7939f")),
        "brainpoolP256r1" => Some((256, "a9fb57dba1eea9bc3e660a909d838d718c397aa3b561a6f7901e0e82974856a7")),
        "brainpoolP256t1" => Some((256, "a9fb57dba1eea9bc3e660a909d838d718c397aa3b561a6f7901e0e82974856a7")),
        "brainpoolP320r1" => Some((320, "d35e472036bc4fb7e13c785ed201e065f98fcfa5b68f12a32d482ec7ee8658e98691555b44c59311")),
        "brainpoolP320t1" => Some((320, "d35e472036bc4fb7e13c785ed201e065f98fcfa5b68f12a32d482ec7ee8658e98691555b44c59311")),
        "brainpoolP384r1" => Some((384, "8cb91e82a3386d280f5d6f7e50e641df152f7109ed5456b31f166e6cac0425a7cf3ab6af6b7fc3103b883202e9046565")),
        "brainpoolP384t1" => Some((384, "8cb91e82a3386d280f5d6f7e50e641df152f7109ed5456b31f166e6cac0425a7cf3ab6af6b7fc3103b883202e9046565")),
        "brainpoolP512r1" => Some((512, "aadd9db8dbe9c48b3fd4e6ae33c9fc07cb308db3b3c9d20ed6639cca70330870553e5c414ca92619418661197fac10471db1d381085ddaddb58796829ca90069")),
        "brainpoolP512t1" => Some((512, "aadd9db8dbe9c48b3fd4e6ae33c9fc07cb308db3b3c9d20ed6639cca70330870553e5c414ca92619418661197fac10471db1d381085ddaddb58796829ca90069")),
        _ => None,
    }
}

/// (name, a, b, n, p) as hex — for matching explicitly-specified curve params.
pub const CURVE_PARAMS: &[(&str, &str, &str, &str, &str)] = &[
    ("P-192", "fffffffffffffffffffffffffffffffefffffffffffffffc", "64210519e59c80e70fa7e9ab72243049feb8deecc146b9b1", "ffffffffffffffffffffffff99def836146bc9b1b4d22831", "fffffffffffffffffffffffffffffffeffffffffffffffff"),
    ("P-224", "fffffffffffffffffffffffffffffffefffffffffffffffffffffffe", "b4050a850c04b3abf54132565044b0b7d7bfd8ba270b39432355ffb4", "ffffffffffffffffffffffffffff16a2e0b8f03e13dd29455c5c2a3d", "ffffffffffffffffffffffffffffffff000000000000000000000001"),
    ("P-256", "ffffffff00000001000000000000000000000000fffffffffffffffffffffffc", "5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b", "ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551", "ffffffff00000001000000000000000000000000ffffffffffffffffffffffff"),
    ("P-384", "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000fffffffc", "b3312fa7e23ee7e4988e056be3f82d19181d9c6efe8141120314088f5013875ac656398d8a2ed19d2a85c8edd3ec2aef", "ffffffffffffffffffffffffffffffffffffffffffffffffc7634d81f4372ddf581a0db248b0a77aecec196accc52973", "fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000ffffffff"),
    ("P-521", "1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc", "51953eb9618e1c9a1f929a21a0b68540eea2da725b99b315f3b8b489918ef109e156193951ec7e937b1652c0bd3bb1bf073573df883d2c34f1ef451fd46b503f00", "1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffa51868783bf2f966b7fcc0148f709a5d03bb5c9b8899c47aebb6fb71e91386409", "1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"),
    ("brainpoolP160r1", "340e7be2a280eb74e2be61bada745d97e8f7c300", "1e589a8595423412134faa2dbdec95c8d8675e58", "e95e4a5f737059dc60df5991d45029409e60fc09", "e95e4a5f737059dc60dfc7ad95b3d8139515620f"),
    ("brainpoolP160t1", "e95e4a5f737059dc60dfc7ad95b3d8139515620c", "7a556b6dae535b7b51ed2c4d7daa7a0b5c55f380", "e95e4a5f737059dc60df5991d45029409e60fc09", "e95e4a5f737059dc60dfc7ad95b3d8139515620f"),
    ("brainpoolP192r1", "6a91174076b1e0e19c39c031fe8685c1cae040e5c69a28ef", "469a28ef7c28cca3dc721d044f4496bcca7ef4146fbf25c9", "c302f41d932a36cda7a3462f9e9e916b5be8f1029ac4acc1", "c302f41d932a36cda7a3463093d18db78fce476de1a86297"),
    ("brainpoolP192t1", "c302f41d932a36cda7a3463093d18db78fce476de1a86294", "13d56ffaec78681e68f9deb43b35bec2fb68542e27897b79", "c302f41d932a36cda7a3462f9e9e916b5be8f1029ac4acc1", "c302f41d932a36cda7a3463093d18db78fce476de1a86297"),
    ("brainpoolP224r1", "68a5e62ca9ce6c1c299803a6c1530b514e182ad8b0042a59cad29f43", "2580f63ccfe44138870713b1a92369e33e2135d266dbb372386c400b", "d7c134aa264366862a18302575d0fb98d116bc4b6ddebca3a5a7939f", "d7c134aa264366862a18302575d1d787b09f075797da89f57ec8c0ff"),
    ("brainpoolP224t1", "d7c134aa264366862a18302575d1d787b09f075797da89f57ec8c0fc", "4b337d934104cd7bef271bf60ced1ed20da14c08b3bb64f18a60888d", "d7c134aa264366862a18302575d0fb98d116bc4b6ddebca3a5a7939f", "d7c134aa264366862a18302575d1d787b09f075797da89f57ec8c0ff"),
    ("brainpoolP256r1", "7d5a0975fc2c3057eef67530417affe7fb8055c126dc5c6ce94a4b44f330b5d9", "26dc5c6ce94a4b44f330b5d9bbd77cbf958416295cf7e1ce6bccdc18ff8c07b6", "a9fb57dba1eea9bc3e660a909d838d718c397aa3b561a6f7901e0e82974856a7", "a9fb57dba1eea9bc3e660a909d838d726e3bf623d52620282013481d1f6e5377"),
    ("brainpoolP256t1", "a9fb57dba1eea9bc3e660a909d838d726e3bf623d52620282013481d1f6e5374", "662c61c430d84ea4fe66a7733d0b76b7bf93ebc4af2f49256ae58101fee92b04", "a9fb57dba1eea9bc3e660a909d838d718c397aa3b561a6f7901e0e82974856a7", "a9fb57dba1eea9bc3e660a909d838d726e3bf623d52620282013481d1f6e5377"),
    ("brainpoolP320r1", "3ee30b568fbab0f883ccebd46d3f3bb8a2a73513f5eb79da66190eb085ffa9f492f375a97d860eb4", "520883949dfdbc42d3ad198640688a6fe13f41349554b49acc31dccd884539816f5eb4ac8fb1f1a6", "d35e472036bc4fb7e13c785ed201e065f98fcfa5b68f12a32d482ec7ee8658e98691555b44c59311", "d35e472036bc4fb7e13c785ed201e065f98fcfa6f6f40def4f92b9ec7893ec28fcd412b1f1b32e27"),
    ("brainpoolP320t1", "d35e472036bc4fb7e13c785ed201e065f98fcfa6f6f40def4f92b9ec7893ec28fcd412b1f1b32e24", "a7f561e038eb1ed560b3d147db782013064c19f27ed27c6780aaf77fb8a547ceb5b4fef422340353", "d35e472036bc4fb7e13c785ed201e065f98fcfa5b68f12a32d482ec7ee8658e98691555b44c59311", "d35e472036bc4fb7e13c785ed201e065f98fcfa6f6f40def4f92b9ec7893ec28fcd412b1f1b32e27"),
    ("brainpoolP384r1", "7bc382c63d8c150c3c72080ace05afa0c2bea28e4fb22787139165efba91f90f8aa5814a503ad4eb04a8c7dd22ce2826", "4a8c7dd22ce28268b39b55416f0447c2fb77de107dcd2a62e880ea53eeb62d57cb4390295dbc9943ab78696fa504c11", "8cb91e82a3386d280f5d6f7e50e641df152f7109ed5456b31f166e6cac0425a7cf3ab6af6b7fc3103b883202e9046565", "8cb91e82a3386d280f5d6f7e50e641df152f7109ed5456b412b1da197fb71123acd3a729901d1a71874700133107ec53"),
    ("brainpoolP384t1", "8cb91e82a3386d280f5d6f7e50e641df152f7109ed5456b412b1da197fb71123acd3a729901d1a71874700133107ec50", "7f519eada7bda81bd826dba647910f8c4b9346ed8ccdc64e4b1abd11756dce1d2074aa263b88805ced70355a33b471ee", "8cb91e82a3386d280f5d6f7e50e641df152f7109ed5456b31f166e6cac0425a7cf3ab6af6b7fc3103b883202e9046565", "8cb91e82a3386d280f5d6f7e50e641df152f7109ed5456b412b1da197fb71123acd3a729901d1a71874700133107ec53"),
    ("brainpoolP512r1", "7830a3318b603b89e2327145ac234cc594cbdd8d3df91610a83441caea9863bc2ded5d5aa8253aa10a2ef1c98b9ac8b57f1117a72bf2c7b9e7c1ac4d77fc94ca", "3df91610a83441caea9863bc2ded5d5aa8253aa10a2ef1c98b9ac8b57f1117a72bf2c7b9e7c1ac4d77fc94cadc083e67984050b75ebae5dd2809bd638016f723", "aadd9db8dbe9c48b3fd4e6ae33c9fc07cb308db3b3c9d20ed6639cca70330870553e5c414ca92619418661197fac10471db1d381085ddaddb58796829ca90069", "aadd9db8dbe9c48b3fd4e6ae33c9fc07cb308db3b3c9d20ed6639cca703308717d4d9b009bc66842aecda12ae6a380e62881ff2f2d82c68528aa6056583a48f3"),
    ("brainpoolP512t1", "aadd9db8dbe9c48b3fd4e6ae33c9fc07cb308db3b3c9d20ed6639cca703308717d4d9b009bc66842aecda12ae6a380e62881ff2f2d82c68528aa6056583a48f3", "7cbbbcf9441cfab76e1890e46884eae321f70c0bcb4981527897504bec3e36a62bcdfa2304976540f6450085f2dae145c22553b465763689180ea2571867423e", "aadd9db8dbe9c48b3fd4e6ae33c9fc07cb308db3b3c9d20ed6639cca70330870553e5c414ca92619418661197fac10471db1d381085ddaddb58796829ca90069", "aadd9db8dbe9c48b3fd4e6ae33c9fc07cb308db3b3c9d20ed6639cca703308717d4d9b009bc66842aecda12ae6a380e62881ff2f2d82c68528aa6056583a48f3"),
];
