//! Poseidon2 hash over BN254, matching `@zkpassport/poseidon2` and
//! barretenberg's `poseidon2::hash`.
//!
//! The permutation (t=4) comes from the `taceo-poseidon2` crate, whose
//! parameters are generated by the same HorizenLabs script barretenberg uses.
//! The sponge below is a port of `FieldSponge` in `@zkpassport/poseidon2`
//! `src/bn254/hash.ts` (rate 3, capacity 1, IV = (input_len << 64) + out_len - 1).
//! Equivalence is enforced by the differential tests.

use ark_bn254::Fr;
use num_bigint::BigUint;
use taceo_poseidon2::bn254::t4::permutation;

const T: usize = 4;
const RATE: usize = T - 1;

struct FieldSponge {
    state: [Fr; T],
    cache: [Fr; RATE],
    cache_size: usize,
    squeeze_mode: bool,
}

impl FieldSponge {
    fn new(domain_iv: Fr) -> Self {
        let mut state = [Fr::from(0u64); T];
        state[RATE] = domain_iv;
        Self {
            state,
            cache: [Fr::from(0u64); RATE],
            cache_size: 0,
            squeeze_mode: false,
        }
    }

    fn perform_duplex(&mut self) -> [Fr; RATE] {
        for i in self.cache_size..RATE {
            self.cache[i] = Fr::from(0u64);
        }
        for i in 0..RATE {
            self.state[i] += self.cache[i];
        }
        self.state = permutation(&self.state);
        [self.state[0], self.state[1], self.state[2]]
    }

    fn absorb(&mut self, input: Fr) {
        if !self.squeeze_mode && self.cache_size == RATE {
            self.perform_duplex();
            self.cache[0] = input;
            self.cache_size = 1;
        } else if !self.squeeze_mode {
            self.cache[self.cache_size] = input;
            self.cache_size += 1;
        } else {
            self.cache[0] = input;
            self.cache_size = 1;
            self.squeeze_mode = false;
        }
    }

    fn squeeze(&mut self) -> Fr {
        if self.squeeze_mode && self.cache_size == 0 {
            self.squeeze_mode = false;
        }
        if !self.squeeze_mode {
            let out = self.perform_duplex();
            self.squeeze_mode = true;
            self.cache = out;
            self.cache_size = RATE;
        }
        let result = self.cache[0];
        for i in 1..self.cache_size {
            self.cache[i - 1] = self.cache[i];
        }
        self.cache_size -= 1;
        self.cache[self.cache_size] = Fr::from(0u64);
        result
    }

    fn hash_fixed_length(input: &[Fr]) -> Fr {
        let iv = Fr::from((input.len() as u128) << 64);
        let mut sponge = Self::new(iv);
        for &x in input {
            sponge.absorb(x);
        }
        sponge.squeeze()
    }
}

pub fn poseidon2_hash_fr(inputs: &[Fr]) -> Fr {
    FieldSponge::hash_fixed_length(inputs)
}

/// Hash arbitrary-precision inputs (reduced mod the BN254 scalar field, as the
/// TS `F1Field` does) and return the result as a BigUint.
pub fn poseidon2_hash(inputs: &[BigUint]) -> BigUint {
    let frs: Vec<Fr> = inputs.iter().map(|b| Fr::from(b.clone())).collect();
    poseidon2_hash_fr(&frs).into()
}
